spring.application.name=llm-gateway

# OpenRouter API
llm.openrouter.api-key=${LLM_OPENROUTER_API_KEY}}
llm.openrouter.base-url=https://openrouter.ai/api/v1/chat/completions

# NVIDIA API
llm.nvidia.api-key=${LLM_NVIDIA_API_KEY}
llm.nvidia.base-url=https://integrate.api.nvidia.com/v1/chat/completions